### ISSUE TITLE
Enabling Ingress Requires Port Override in Config

### ISSUE THREAD

**Issue by kacy** [meilisearch/meilisearch-kubernetes#102]
**Description**
In the event that an end developer wants to [enable ingress](https://github.com/meilisearch/meilisearch-kubernetes/blob/main/charts/meilisearch/values.yaml#L53), they also have to [override the Service Port to port 80](https://github.com/meilisearch/meilisearch-kubernetes/blob/main/charts/meilisearch/values.yaml#L46) since it's [hardcoded](https://github.com/meilisearch/meilisearch-kubernetes/blob/main/charts/meilisearch/templates/ingress.yaml#L51) in the template. 

I would have opened a PR, but I'm not sure how the maintainers want to address it. We could tackle it in documentation, assume port 80 on the service port, or alter the ingress template to support the Helm variable.

**Expected behavior**
What you expected to happen.

**Current behavior**
Enabling the ingress flag results in the following error: `Translation failed: invalid ingress spec: could not find port "&ServiceBackendPort{Name:,Number:80,}" in service "default/meilisearch"`

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- Meilisearch version: main branch
- meilisearch-kubernetes version: main branch

**Comment by alallema** [comment]
Hi @kacy,
Thank you for raising this issue! Indeed, this is not practical at all. I think the best solution is to allow the Helm template to set a variable with the default value at 7700.
If you still want to open a PR to fix this it would be so great ❤️

**Comment by kacy** [comment]
Sure thing. I made the change here https://github.com/meilisearch/meilisearch-kubernetes/pull/103

Let me know if you have different thoughts. Thanks!
