### ISSUE TITLE
Installation with enabled ingress fails on Kubernetes >=1.19

### ISSUE THREAD

**Issue by johankok** [meilisearch/meilisearch-kubernetes#104]
**Description**

When installing the chart with ingress enabled, Helm refuses to install the application with the error below.

This issue is introduced by #103. `.Values.service.port` exists in the global scope, but not in within the `.range` block. I've created a Pull Request to resolve this.

**Expected behavior**
Successfully deployed helm chart.

**Current behavior**

```
[johan@fedora1 ~]$ helm upgrade -i fancy-instance-name --set ingress.enabled=true meilisearch/meilisearch
Error: UPGRADE FAILED: template: meilisearch/templates/ingress.yaml:51:34: executing "meilisearch/templates/ingress.yaml" at <.Values.service.port>: can't evaluate field Values in type interface {}
```

**Environment (please complete the following information):**
- OS: Fedora
- Meilisearch version: v0.26.0
- meilisearch-kubernetes version: 0.1.27

**Comment by alallema** [comment]
Hi @johankok,
Thank you for raising this issue and for your PR!
