### ISSUE TITLE
BUG: Chart renders Invalid YAML when Ingress option is enabled

### ISSUE THREAD

**Issue by churdstheword** [meilisearch/meilisearch-kubernetes#118]
**Description**
The helm chart yields invalid YAML when the ingress option is enabled. 

**Expected behavior**
The helm chart should yield valid k8s manifests with valid YAML syntax. 

**Current behavior**
Running the following command:
```bash
helm template meilisearch/meilisearch --set=ingress.enabled=true --version 0.1.34
```

Yields the following error:
```bash
Error: YAML parse error on meilisearch/templates/ingress.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context
```

If you add the debug flag to the previous command, you can see the invalid syntax  in the output:
```bash
helm template meilisearch/meilisearch --set=ingress.enabled=true --version 0.1.34 --debug
```

![image](https://user-images.githubusercontent.com/26151018/170292926-2fec4213-0c6f-4af7-b1d0-760c21a2f139.png)

**Screenshots or Logs**
N/A

**Environment (please complete the following information):**
- OS: Window/Linux (Ubuntu) via WSL2
- Meilisearch version: 0.27.1
- meilisearch-kubernetes version: 0.1.34

**Comment by alallema** [comment]
Thanks @churdstheword,
For raising this issue!

**Comment by Tchoupinax** [comment]
The job has failed : https://github.com/meilisearch/meilisearch-kubernetes/runs/6919025401?check_suite_focus=true :(

**Comment by alallema** [comment]
Hi @Tchoupinax,
Good catch thank you! It should be good now

**Comment by Tchoupinax** [comment]
Thank you @alallema!

**Comment by Tchoupinax** [comment]
Hi again @alallema,

It seems that the chart is still not published.
I gave a look on the pipeline and [here](https://github.com/meilisearch/meilisearch-kubernetes/runs/6939306280?check_suite_focus=true), I found that:

```
Run helm/chart-releaser-action@v1.2.0
Run owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
Looking up latest tag...
Discovering changed charts since 'meilisearch-0.1.35'...
Nothing to do. No chart changes detected.
```
I think that you fixed the CI and restarted it but the git difference was already passed and so the CI did not push the chart. :(

**Comment by alallema** [comment]
Oopsy ...
Thanks again @Tchoupinax ❤️ 
This time it should be fixed!

**Comment by Tchoupinax** [comment]
It seems good :)
Thank you for your reactivity ❤️
