### ISSUE TITLE
Configure a helm char repo as part of helm hub

### ISSUE THREAD

**Issue by renehernandez** [meilisearch/meilisearch-kubernetes#13]
Set up a helm chart repository and integrate it with Helm Hub following the guide: https://github.com/helm/hub/blob/master/Repositories.md

That way, developers can use the chart without the need to clone the repository and instead referencing the chart through the meilisearch helm repo index

Example:
```
helm repo add meilisearch <url>
helm install my-meilisearch meilisearch/meilisearch
```

**Comment by deshetti** [comment]
@renehernandez Helm Hub / Artifact Hub inclusion just seems to be for the repositories to be available in for `helm search hub meilisearch`. Steps from the link you mentioned are for the inclusion of the existing repository to Artifact Hub.

Prior to that we need to create setup the chart in its own repository by following the steps here: https://helm.sh/docs/topics/chart_repository/

That way the users can install charts like you mentioned using the following commands:

```
helm repo add meilisearch <repository-url>
helm install my-meilisearch meilisearch/meilisearch
```

**Comment by renehernandez** [comment]
@deshetti Good catch! I think we can reuse this repository for it. According to this [section](https://helm.sh/docs/topics/chart_repository/#github-pages-example), we could leverage GIthub Pages to publish from a gh-pages branch

**Comment by eskombro** [comment]
It seems like a great idea to modify this repository into use it as a chart repository, and use GitHub pages to serve the chart(s)!

**Comment by eskombro** [comment]
Helm Hub Moving To Artifact Hub

https://helm.sh/blog/helm-hub-moving-to-artifact-hub/

**Comment by deshetti** [comment]
@eskombro would it be possible for you to implement this? https://helm.sh/docs/topics/chart_repository/#github-pages-example

**Comment by eskombro** [comment]
Sure! I take note and I'll have a look at it soon (a little busy atm)! I'll let you know when I get into it :)
