### ISSUE TITLE
Remove the possibility to set `replicaCount` to a value other than "1"?

### ISSUE THREAD

**Issue by c0bra** [meilisearch/meilisearch-kubernetes#188]
According to various closed issues, Meilisearch does not support high availability when self-hosted, and using more than one replica can cause things to break.

That being said, should the `replicaCount` value be removed and just hard-code it to `1` for now?

https://github.com/meilisearch/meilisearch-kubernetes/blob/main/charts/meilisearch/templates/statefulset.yaml#L8C39-L8C39

**Comment by alallema** [comment]
Hi @c0bra,
Thanks for raising this issue. You are right it could be a good thing to do that.
