### ISSUE TITLE
Chart updates which require a manual backup restore should be major updates?

### ISSUE THREAD

**Issue by pat-s** [meilisearch/meilisearch-kubernetes#201]
**Description**
We're using `meilisearch` since v1.0.0 and it looks like that every minor version release requires a manual backup and restore and the update won't just work out of the box.

This becomes an issue if the chart also only releases a minor update as a lot of infra-automation tools aim to auto-merge minor and patch updates (e.g. `renovate`) as these release types usually indicate non-breaking changes.
Now if this happens for meilisearch the update will fail as one cannot simply update from 1.1.0 to 1.2.0 and so on. I assume this will be the case for future `meilisearch` releases as well?
 
My proposal would be to release a major version of the chart if a new `meilisearch` release is included which does not support auto-updating. This way, automation won't do the update and manual work is required - which at least keeps the running/old instance working.

**Comment by pat-s** [comment]
Now what I described above happened with the 0.2.7 chart release, bumping to meilisearch 1.4 which does not work OOB...

**Comment by brunoocasali** [comment]
As far as I remember, based on our versioning policy https://github.com/meilisearch/engine-team/blob/main/resources/versioning-policy.md yes, for every new update, you will have to make a dump and restart your infra. I agree that's not the best, but we have yet to find a solution.

So, I am keen to agree with you to release a major version of the chart for each new release of meilisearch that is not a patch.
This will be an "alert" to the users that they can't simply run a chart update, and it will work. They need to watch the changelog.

Unless @curquiza changes my mind on the subject I think we can do it for the next releases.

**Comment by curquiza** [comment]
Agreed with you if this is something the community prefers!

**Comment by brunoocasali** [comment]
Ok, cool, let's do it then! 

I don't think we have to change it anything is more a mindset/process than a real code-change, so the next release it will start following this pattern. 

Thanks for your inputs @pat-s and @curquiza ;)
