### ISSUE TITLE
Cleanup manifests with the info related to Helm

### ISSUE THREAD

**Issue by deshetti** [meilisearch/meilisearch-kubernetes#21]
I was looking at the manifests and not sure if we need these lines? I am thinking the reason for manifests is to install on Kubernetes without Helm.

```
helm.sh/chart: meilisearch-0.1.4
app.kubernetes.io/managed-by: Helm
```

In fact, they are wrong IMO, cuz they are not managed by Helm if the manifest files are installed separately on Kubernetes.

**Comment by eskombro** [comment]
Totally rigth @deshetti, they were included because the manifests were auto-generated from the Helm chart, and they can absolutely be removed :)
