### ISSUE TITLE
Installing more than one replica doesn't work

### ISSUE THREAD

**Issue by deshetti** [meilisearch/meilisearch-kubernetes#25]
I am trying to install using helm chart on DigitalOcean, but I believe the same would happen on GCS or AWS since the default storageclass on these providers doesn't support ReadWriteMany access mode.

When I tried installing the chart using `replicaCount: 2`, I see that the first pod is created and running as expected and the second one is stuck in the status `ContainerCreating`

Following the is the events when I execute describe command on the pod:

```
Events:
  Type     Reason              Age    From                     Message
  ----     ------              ----   ----                     -------
  Normal   Scheduled           4m52s  default-scheduler        Successfully assigned dega/meili-meilisearch-1 to pool-8gb4cpu-3stpq
  Warning  FailedAttachVolume  4m52s  attachdetach-controller  Multi-Attach error for volume "pvc-f256af54-5cb1-451c-86f8-d03ba4861014" Volume is already used by pod(s) meili-meilisearch-0
  Warning  FailedMount         2m49s  kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[meili-meilisearch-token-zd9rl data]: timed out waiting for the condition
  Warning  FailedMount         33s    kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data meili-meilisearch-token-zd9rl]: timed out waiting for the condition
```

**Comment by eskombro** [comment]
Hey @deshetti,

Indeed, this seems to be an issue, but as for now MeiliSearch itself wouldn't support it either, since it desn't allow reading from the same database by several instances. The core team is workin on a high availability and consensus feature that will let us create several instances for replication and consistency. This should be available in the next few months (can't tell what would be the eta exactly), but as it should be a consensus algorythm instances would own their own isolated storage and at the same time data would be syncronised in different instances of a cluster, fix this problem (I think). WDYT?

**Comment by simonxxz** [comment]
Hi guys! I'm also expecting a real-time synchronization feature for mutiple databases. This would be a lot better to use in production than using snapshots/dumps.

**Comment by eskombro** [comment]
Hi @simonxxz 

This is in MeiliSearch's roadmap indeed, but as for now, the engine is not capable of providing replication and a distributed deployment. If this feature is important for you I invite you to give it a little upvote in the roadmap, but be reassured that the team is working on that :)

[High Availability on our roadmap](https://roadmap.meilisearch.com/c/24-high-availibility)

**Comment by laurenz-glueck** [comment]
Is there any update on this topic or an eta?

**Comment by alallema** [comment]
Hi @laurenz-glueck,
Thanks for asking. The team has planned to move forward on the issue around the end of the year but it is possible that it will change. Nevertheless, it is still a goal that we would really like to achieve.

**Comment by alallema** [comment]
Closing due to lack of answer, feel free to re-open if needed of course 🙂

**Comment by alallema** [comment]
_Information update:_
For now, Meilisearch doesn't manage high availability, and for the moment the team doesn't work on it anymore. I close this topic until the subject is put back in the roadmap.
