### ISSUE TITLE
Liveness and Readiness Probe Failing with Meilisearch v.0.17.0 on production

### ISSUE THREAD

**Issue by HelmutLety** [meilisearch/meilisearch-kubernetes#27]
With Meilisearch v.0.17.0, when production is enabled, the frontend is disabled.
The readiness and liveness Probe in Kubernetess will fail, because it is a httpGet on the frontend

**Comment by HelmutLety** [comment]
I may have found a Solution.
Using           _tcpSocket_ instead as _httpGet_ in the probes in Statefulset.
Gonna do a PR tomorrow

**Comment by eskombro** [comment]
Hi @HelmutLety 

Well spotted, you are absolutely right! An httpGet on `/` now returns a 404, which makes the `livenessProbe` broken. Thanks for this feedback and will be glad to check your PR anytime, please ping me :)

**Comment by eskombro** [comment]
We should be using the [get health](https://docs.meilisearch.com/references/health.html#get-health) route IMO
