### ISSUE TITLE
service:NodePort does not match the correct NodePort

### ISSUE THREAD

**Issue by simonxxz** [meilisearch/meilisearch-kubernetes#47]
I defined the #NodePort to be exposed, for example, 31009, in values.yaml.  But when I installed the helm chart, the real NodePort ranged from 31000 to 33000 and was never the specified 31009.

**Comment by eskombro** [comment]
Hi @simonxxz 

Con you show us an example of your configuration?

**Comment by simonxxz** [comment]
> Hi @simonxxz
> 
> Can you show us an example of your configuration?

Here is my config:
service:
  type: NodePort
  port: 7700
  NodePort: 31009

Is there anything config I have to add to make nodeport work correctly?

**Comment by eskombro** [comment]
HI @simonxxz 

Indeed, the chart is not prepared to add the `nodePort` field, so the port you are specifying is basically ignored. I detailed this on this issue: https://github.com/meilisearch/meilisearch-kubernetes/issues/50

Feel free to add any useful info in there, and if you feel like doing a fix on it it would be amazing to have your contribution! :)

(Closing in favor of #50, feel free to re-open if needed)
