### ISSUE TITLE
Feature request: volume mounting

### ISSUE THREAD

**Issue by simonxxz** [meilisearch/meilisearch-kubernetes#48]
I really like the volume mounting feature to bind data.ms when using Meili in docker. Is there a way in values.yaml to do the same thing?

**Comment by eskombro** [comment]
Hi @simonxxz 

Sorry for the late answer! Indeed, in the Helm chart there is a Persistance option that is disabled by default but you can enable it in `values.yaml`

Take a look at this: https://github.com/meilisearch/meilisearch-kubernetes/blob/master/charts/meilisearch/values.yaml#L44-L55

This will request a volume creation in the StatefulSet as you can see here:

https://github.com/meilisearch/meilisearch-kubernetes/blob/master/charts/meilisearch/templates/statefulset.yaml#L28-L33

I hope this fits your need :)

**Comment by simonxxz** [comment]
> Hi @simonxxz
> 
> Sorry for the late answer! Indeed, in the Helm chart there is a Persistance option that is disabled by default but you can enable it in `values.yaml`
> 
> Take a look at this: https://github.com/meilisearch/meilisearch-kubernetes/blob/master/charts/meilisearch/values.yaml#L44-L55
> 
> This will request a volume creation in the StatefulSet as you can see here:
> 
> https://github.com/meilisearch/meilisearch-kubernetes/blob/master/charts/meilisearch/templates/statefulset.yaml#L28-L33
> 
> I hope this fits your need :)

Thanks, it works!

**Comment by curquiza** [comment]
Closing the issue then! Feel free to re-open
