### ISSUE TITLE
GKE ingress health check fails

### ISSUE THREAD

**Issue by alimoabd2127** [meilisearch/meilisearch-kubernetes#56]
If someone is to create a GKE ingress, it requires that the health check endpoint respond with a code 200 as described [here](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#def_inf_hc). Currently, the workaround is to switch back to the / endpoint rather than the /health because / responds with a 200 rather than a 204.
```
readinessProbe:
  httpGet:
    path: /
    port: 7700
```
I haven't looked at the helm charts, but I did modify the /manifest/meilisearch.yaml file to include the above change and that allowed me to pass the GKE ingress health checks.

**Comment by eskombro** [comment]
@alimoabd2127 

The `/` route sends a 200 only when in development environment, but as soon as you run it in production environment, this behavior changes, and this workaround won't be a solution anymore. This should be indeed treated in MeiliSearch core itself, to fix the problem!

Thanks for the issue!

**Comment by curquiza** [comment]
Hello @alimoabd2127!
A fix will be done in a near future to fix this issue in the [MeiliSearch repo](https://github.com/meilisearch/Meilisearch)!
Closing this issue since it's related to this repo!
And thanks @alimoabd2127 for the workaround
