### ISSUE TITLE
Checks stuck in Waiting for status to be reported

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-kubernetes#70]
**Description**
When using the automatic fixing tool by comment for sync chart, Github checks/actions get stuck in:
`Expected — Waiting for status to be reported`
Bors get stuck too after a `bors try` even if the checks have passed and it never comments with:
`Build succeeded`

**Comment by alallema** [comment]
Hi @carlreid!
I try your fixing tool by comment here #69 and the commit works well but unfortunately, it seems to break the checks after launch it. I guess that it's because Github can find the other checks in this [job](https://github.com/meilisearch/meilisearch-kubernetes/pull/69/checks). I also think that if I commit again it will get unstuck it but I'm not sure.
If you had any idea of the problem I would be very grateful.

**Comment by carlreid** [comment]
Hey, I'm not sure how you guys are using bors and what it does.

But it seems like it's maybe getting stuck because the check only runs against `main`. I would try also adding the `trying` branch and see if that resolves the issue.

It does seem very odd though 🤔

**Comment by alallema** [comment]
@carlreid,
Thanks for your help again! I think the problem is that jobs can't launch other jobs to avoid infinite loops. On the other hand, the branch settings require status checks to pass before merging so somewhere it gets stuck.
For now, I will remove the comment fixing tool even if I like it, keep the check chart and add it to the mandatory Bors checks.

**Comment by carlreid** [comment]
I don't think a job is running any other jobs. The comment will trigger the sync job to run, which will update the manifest and commit it to the source. Which will then trigger the check job to run again (as would any commit). But that's the end of the flow from what I can remember. Make sure to ignore if `Sync chart manifest on comment` is ran though, if bors is setup to check it

But if it is causing too much trouble, then I don't mind if you remove it either 🙂

**Comment by alallema** [comment]
It's working! You were right 🎉
