### ISSUE TITLE
Can't run Meili with persistance enabled

### ISSUE THREAD

**Issue by ook** [meilisearch/meilisearch-kubernetes#74]
**Description**

Using latest helm chart, on a k8s v1.18.17 cluster, values.yaml only set the storage class (that target a kadalu.io working storage class).
The error occurs identically on production and development mode.
If I remove the persistence, Meili works as expected.
The Kadalu server works perfectly (dynamic provisioning, the generated PV is functional)

**Expected behavior**

Meili starting.

**Current behavior**

Meili doesn't start with error in logs: `Error: heed error; Value too large for data type (os error 75)`
Pod put in Crashloop Backoff state.

**Environment (please complete the following information):**
- Kubernetes cluster v1.18.17 on 11 baremetals nodes managed with rancher2
- MeiliSearch version: v0.19.0
- meilisearch-kubernetes version: meilisearch-0.1.14

**Comment by alallema** [comment]
Hi @ook
Thank you for report this issue and sorry for the delay.
I try to reproduce your issue but I can get it.
Can I have a detail of the more specific steps you have done?
Also `Error: heed error; Value too large for data type (os error 75)` came from the core so the engine Meilisearch.
Maybe the Meilisearch engine doesn’t support your architecture and it will be really interesting to know why.
Did you try the latest version of meilisearch: v0.20.0?

**Comment by ook** [comment]
Hi @alallema 
As you suggested, I forced tag `v0.20.0` … and it works with the persistence!
So, I could tell that for helm meilisearch-0.1.14 we need to use tag >= v0.20.0 to work with persistence.

Thank you.
