### ISSUE TITLE
New path for data.ms?

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-kubernetes#89]
Since v0.24.0, MeiliSearch runs using the `meili` users in the docker container. This involves a change regarding the path of the `data.ms` folder by default. It's now `/home/meili/data.ms` instead of `/data.ms`

Shouldn't we change the lines here according to the new path? I'm really asking, I don't know the answer, you have to check @alallema 😄 

https://github.com/meilisearch/meilisearch-kubernetes/blob/9551441e118d8a391656357970aef38c46a850a9/charts/meilisearch/values.yaml#L60-L75

Related to: https://github.com/meilisearch/MeiliSearch/issues/1969

**Comment by alallema** [comment]
@curquiza, I'm not sure either but I think this path is where it will be mounted.
I will check that.

**Comment by thanhtoan1196** [comment]
I think the path needs to be changed, because currently persistence is not working, after my pod is shut down, there is no data left

**Comment by alallema** [comment]
Hi @thanhtoan1196,
Sorry about this and thank you for letting us know.

**Comment by curquiza** [comment]
In v0.25.0, the path of data.ms will be back to `/` and not `/home/meili`. More detail here to know why: https://github.com/meilisearch/MeiliSearch/issues/2051

**Comment by curquiza** [comment]
I think we can close this issue @alallema then

**Comment by alallema** [comment]
I would like to check if the persistence works well with the v0.25.0 before.

**Comment by alallema** [comment]
Hi @thanhtoan1196,
Did you solve your problem? I just tested persistence with `v0.1.26` if I shut down my pod it restarts with all the data.

**Comment by alallema** [comment]
I closed this issue because it is no longer relevant and no problems have been reported since.
