### ISSUE TITLE
Recommended way to do backups?

### ISSUE THREAD

**Issue by fr3fou** [meilisearch/meilisearch-kubernetes#92]
I want to backup my MeiliSearch data but not sure what approach to take. I was thinking of something using a cron job that uploads the dump to S3. What's the recommended way to do this?

**Comment by alallema** [comment]
Hi @fr3fou,
Sorry for the delay in responding. We don't have a specific recommended way, you can indeed make schedule snapshots or make dumps regularly. You can check the documentation on [backup](https://docs.meilisearch.com/learn/advanced/snapshots_vs_dumps.html) to see. Do not hesitate to tell us if you find a good solution 😊.

**Comment by fr3fou** [comment]
I was thinking of setting up a Kubernetes `CronJob` (https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) using some kind of Docker image that creates a dump then uploads it to S3 as I mentioned in the original issue. However I was wondering if there's an official image that does something similar to this or a community one.

**Comment by alallema** [comment]
There is no such thing, for now, we have this repo for Kubernetes clusters and an official docker image. I don't know anything about something like that in the community but it would be a great addition!

**Comment by alallema** [comment]
As the question has been answered, I'm closing this repo.
